apiVersion: v1
data:
  application.yaml: |-
    spring:
      application:
        name: meeting
    server:
      port: 8080
    management:
      endpoints:
        web:
          exposure:
            include: "*"
kind: ConfigMap
metadata:
  name: meeting-configmap-kb7744f4cb
---
apiVersion: v1
kind: Service
metadata:
  name: meeting
spec:
  ports:
  - name: http-meeting
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: meeting
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: meeting
    version: 1cf65fc
  name: meeting-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meeting
  template:
    metadata:
      labels:
        app: meeting
        version: 1cf65fc
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: meeting-configmap-kb7744f4cb
        image: eu.gcr.io/vote-of-confidence-233210/meeting@1cf65fc
        name: meeting
        ports:
        - containerPort: 8080
          name: http
        resources:
          requests:
            cpu: 50m
        volumeMounts:
        - mountPath: /etc/deployment/application.yaml
          name: config-volume
          readOnly: true
          subPath: application.yaml
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: application.yaml
            path: application.yaml
          name: meeting-configmap-kb7744f4cb
        name: config-volume
